import type { AppData } from './types';
import { dateOffset, localDate } from './utils';
export function createDemoData(): AppData {
 const today = localDate();
 return { version: 1,
 settings: { name: 'Alex', appearance: 'warm', accent: 'peach', glass: 68, blur: 18, motion: true, neumorphism: true, focusMinutes: 50, weeklyTarget: 20 },
 subjects: [
 {id:'cs',name:'Computer Science',color:'#d9869d',icon:'Laptop',chapters:[{id:'algorithms',title:'Algorithms & complexity',mastery:78,lastReviewed:dateOffset(-3),nextReview:today,question:'What does O(log n) tell us about an algorithm?',answer:'The number of operations grows logarithmically with input size. Doubling the input adds a constant amount of work.',exercise:'How many comparisons are needed in the worst case to binary-search 1,024 sorted elements?',solution:'At most 11 comparisons, including the final comparison (floor(log₂ 1024) + 1).'}, {id:'structures',title:'Data structures',mastery:86,lastReviewed:dateOffset(-1),nextReview:dateOffset(3),question:'When would you use a hash map?',answer:'For fast key-based lookups, insertions, and deletions, averaging O(1).'}]},
 {id:'math',name:'Mathematics',color:'#e9a179',icon:'Sigma',chapters:[{id:'complex',title:'Complex numbers',mastery:43,lastReviewed:dateOffset(-5),nextReview:today,question:'How do you express a complex number in polar form?',answer:'z = r(cos θ + i sin θ) = r e^(iθ), where r is the modulus and θ is the argument.',exercise:'Write 1 + i in polar form.',solution:'√2 e^(iπ/4). Its modulus is √2 and its argument is π/4.'},{id:'sequences',title:'Sequences & induction',mastery:81,lastReviewed:dateOffset(-2),nextReview:dateOffset(2),question:'What are the two main steps in mathematical induction?',answer:'Prove the base case, then prove that the statement for n implies the statement for n+1.'}]},
 {id:'reading',name:'Reading & Research',color:'#ad93d3',icon:'BookOpen',chapters:[{id:'research',title:'Critical reading',mastery:91,lastReviewed:dateOffset(-1),nextReview:dateOffset(5),question:'What makes a source reliable?',answer:'Transparent methods, relevant expertise, verifiable evidence, and independent corroboration.'}]},
 {id:'language',name:'Language Learning',color:'#98b8df',icon:'Globe',chapters:[{id:'vocab',title:'Academic vocabulary',mastery:46,lastReviewed:dateOffset(-7),nextReview:today,question:'What is the difference between imply and infer?',answer:'A speaker implies a meaning. A listener infers the meaning from evidence.'}]}
 ],
 tasks: [
 {id:'t1',title:'Read research paper',subjectId:'reading',quadrant:'do',done:true,due:today,minutes:60,difficulty:2,energy:'medium',notes:'Read the abstract first, then annotate the main argument.',subtasks:[],recurrence:'none'},
 {id:'t2',title:'Complete assignment',subjectId:'cs',quadrant:'do',done:true,due:today,minutes:90,difficulty:3,energy:'high',notes:'Review complexity before submission.',subtasks:[],recurrence:'none'},
 {id:'t3',title:'Revise key concepts',subjectId:'math',quadrant:'do',done:false,due:today,minutes:60,difficulty:3,energy:'high',notes:'Start with complex numbers. Work without notes.',subtasks:[{id:'sub1',title:'Review polar form',done:false},{id:'sub2',title:'Solve 5 exercises',done:false}],recurrence:'none'},
 {id:'t4',title:'Build project prototype',subjectId:'cs',quadrant:'plan',done:false,due:dateOffset(2),minutes:120,difficulty:4,energy:'high',notes:'Build one complete user flow.',subtasks:[],recurrence:'none'},
 {id:'t5',title:'Practice English vocabulary',subjectId:'language',quadrant:'inbox',done:false,due:today,minutes:25,difficulty:1,energy:'low',notes:'Review this week’s 20 words.',subtasks:[],recurrence:'daily'},
 {id:'t6',title:'Plan tomorrow',subjectId:'',quadrant:'delegate',done:false,due:today,minutes:15,difficulty:1,energy:'low',notes:'Choose three priorities.',subtasks:[],recurrence:'daily'},
 {id:'t7',title:'Prepare mathematics exam',subjectId:'math',quadrant:'inbox',done:false,due:dateOffset(5),minutes:90,difficulty:4,energy:'high',notes:'Sequences, complex numbers, and induction.',subtasks:[],recurrence:'none'}
 ],
 events:[{id:'e1',title:'Read research paper',date:today,time:'09:00',minutes:60,subjectId:'reading',taskId:'t1'},{id:'e2',title:'Complete assignment',date:today,time:'10:30',minutes:90,subjectId:'cs',taskId:'t2'},{id:'e3',title:'Revise key concepts',date:today,time:'13:00',minutes:60,subjectId:'math',taskId:'t3'},{id:'e4',title:'Build project prototype',date:dateOffset(1),time:'15:00',minutes:120,subjectId:'cs',taskId:'t4'},{id:'e5',title:'Mathematics exam',date:dateOffset(5),time:'09:00',minutes:120,subjectId:'math'}],
 sessions: Array.from({length:12},(_,i)=>({id:`s${i}`,date:dateOffset(-Math.floor(i/2)),minutes:[50,25,80,40,60,50,45,25,50,90,35,50][i],distractions:i%3,taskId:['t1','t2','t3','t4'][i%4],mode:'Deep Work'})),
 grades:[{id:'g1',subjectId:'math',title:'Sequences & induction',score:16.5,outOf:20,coefficient:2,date:dateOffset(-7),errors:['Calculation'],chapter:'Sequences'},{id:'g2',subjectId:'cs',title:'Algorithms assessment',score:18,outOf:20,coefficient:2,date:dateOffset(-3),errors:['Time management']},{id:'g3',subjectId:'reading',title:'Research essay',score:18.5,outOf:20,coefficient:1,date:dateOffset(-2),errors:[]},{id:'g4',subjectId:'language',title:'Academic writing',score:15,outOf:20,coefficient:1,date:dateOffset(-5),errors:['Knowledge']}],
 goals:[{id:'goal1',title:'A little better, every day.',vision:'Build a calm, consistent study practice.',due:dateOffset(30),milestones:[{id:'m1',title:'Build my weekly study routine',done:true},{id:'m2',title:'Complete 10 focus sessions',done:true},{id:'m3',title:'Master complex numbers',done:false},{id:'m4',title:'Finish a timed practice exam',done:false}]},{id:'goal2',title:'18+ in mathematics',vision:'Understand deeply. Perform confidently.',due:dateOffset(60),milestones:[{id:'m5',title:'Master sequences',done:true},{id:'m6',title:'Review complex numbers',done:false},{id:'m7',title:'Complete 3 practice papers',done:false}]}],
 notes:[{id:'n1',title:'Complex numbers, simply.',body:'A complex number brings two dimensions together: a real part and an imaginary part.\n\nz = a + bi\n\nThe modulus measures distance from the origin. The argument measures direction.\n\nPolar form: z = r · e^(iθ)\n\nRemember: multiplication rotates and scales.',subjectId:'math',kind:'Course',updatedAt:new Date().toISOString(),links:['n2']},{id:'n2',title:'The art of deliberate practice',body:'Choose one specific weakness.\nWork just beyond your comfort zone.\nGet immediate feedback.\nRepeat with an adjustment.\n\nProgress comes from attention, not just repetition.',subjectId:'reading',kind:'Reflection',updatedAt:new Date().toISOString(),links:['n1']},{id:'n3',title:'Binary search — mental model',body:'Start with a sorted collection.\nCheck the middle value.\nDiscard the half that cannot contain your target.\nRepeat.\n\nTime: O(log n). Space: O(1) for the iterative version.',subjectId:'cs',kind:'Formula',updatedAt:new Date().toISOString(),links:[]}],
 resources:[{id:'r1',title:'Linear algebra, beautifully explained',url:'https://www.3blue1brown.com/topics/linear-algebra',subjectId:'math',kind:'Video',starred:true},{id:'r2',title:'Introduction to algorithms',url:'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/',subjectId:'cs',kind:'Course',starred:true},{id:'r3',title:'Academic writing guide',url:'https://owl.purdue.edu/owl/general_writing/academic_writing/index.html',subjectId:'language',kind:'Article',starred:false}],
 reviews:[]
 };
}
