'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Target,CalendarDays,BookOpen,Sparkles,Feather,Headphones,Pause,Play,Coffee,Leaf,AudioLines,ChevronLeft,ChevronRight,Flame,ArrowUpRight,MoreHorizontal,Laptop,Sigma,Globe,Plus,Check} from 'lucide-react';
import {useStore} from '@/lib/store';
import {useFocus} from '@/lib/focus';
import {dateOffset,duration,localDate,uid} from '@/lib/utils';
import {Panel,Progress} from './ui';
const subjectIcons=[Laptop,Sigma,BookOpen,Globe];
export function Dashboard(){
 const {data,update}=useStore(); const focus=useFocus();
 const [now,setNow]=useState<Date|null>(null);useEffect(()=>{setNow(new Date());},[]);
 const today=localDate();const minutes=data.sessions.filter(s=>s.date>=dateOffset(-6)).reduce((a,s)=>a+s.minutes,0);const weekSessions=data.sessions.filter(s=>s.date>=dateOffset(-6));
 const tasks=data.tasks.slice(0,6);const done=data.tasks.filter(t=>t.done).length;
 const total=data.sessions.reduce((a,s)=>a+s.minutes,0);const distractionCount=data.sessions.reduce((a,s)=>a+s.distractions,0);const focusRate=total?Math.max(0,Math.round((total-distractionCount*2)/total*100)):0;
 const bars=Array.from({length:7},(_,i)=>{const date=dateOffset(i-6);const dateObj=new Date(`${date}T12:00:00`);return {day:dateObj.toLocaleDateString('en-US',{weekday:'short'}),minutes:data.sessions.filter(s=>s.date===date).reduce((a,s)=>a+s.minutes,0)};});
 const maxBar=Math.max(120,...bars.map(b=>b.minutes));
 let streak=0;for(let i=0;i<366;i++){if(data.sessions.some(s=>s.date===dateOffset(-i)))streak++;else if(i>0)break;}
 const goal=data.goals[0];const goalProgress=goal&&goal.milestones.length?Math.round(goal.milestones.filter(m=>m.done).length/goal.milestones.length*100):0;
 return <div className="dashboard"><div className="dashboard-hero"><div className="greeting"><p className="eyebrow">Good {now&&now.getHours()>=17?'evening':now&&now.getHours()>=12?'afternoon':'morning'}</p><h1>Same page.<br/>Higher standards.</h1><p>Plan deeper. Focus longer. Build a better you.</p><div className="quick-actions"><Link href="/focus" className="btn btn-primary"><Target size={15}/>Focus</Link><Link href="/calendar" className="btn"><CalendarDays size={15}/>Plan</Link><Link href="/revision" className="btn"><BookOpen size={15}/>Study</Link><Link href="/tasks?new=1" className="btn"><Sparkles size={15}/>Create</Link><Link href="/strategy" className="btn"><Feather size={15}/>Reflect</Link></div></div><Panel className="hero-quote"><span className="quote-mark">“</span><p>Discipline today<br/>creates the freedom<br/>you want tomorrow.</p><span>—</span></Panel><div className="signature">A Higher You.<span/></div></div>
 <div className="dashboard-grid"><div className="dashboard-center"><div className="dashboard-top"><Panel className="focus-card"><div className="panel-header"><p className="eyebrow"><span className="tiny-icon peach"><Headphones size={14}/></span>Focus session</p><Link className="icon-button" href="/focus" aria-label="Open focus session"><MoreHorizontal size={18}/></Link></div><div className="focus-content"><div><div className="dashboard-timer">{String(Math.floor(focus.seconds/60)).padStart(2,'0')}:{String(focus.seconds%60).padStart(2,'0')}</div><p>{focus.mode} · Stay present</p><button className="btn btn-primary timer-button" onClick={focus.toggle}>{focus.running?<Pause size={17} fill="currentColor"/>:<Play size={17} fill="currentColor"/>}{focus.running?'Pause':'Begin focus'}</button></div><Link href="/focus" className="focus-ring" aria-label="Open focus timer" style={{'--progress':`${(1-focus.seconds/focus.totalSeconds)*360}deg`} as React.CSSProperties}><div><span>Focus</span><strong>{data.sessions.filter(s=>s.date===today).length} / 4</strong></div></Link></div><div className="focus-modes">{[{label:'Deep Work',icon:Target,minutes:data.settings.focusMinutes},{label:'Short Break',icon:Coffee,minutes:5},{label:'Long Break',icon:Leaf,minutes:15}].map(m=><button key={m.label} className={focus.mode===m.label?'selected':''} onClick={()=>{focus.setMode(m.label);focus.selectDuration(m.minutes);}}><m.icon size={15}/><span>{m.label}</span></button>)}<Link href="/focus"><AudioLines size={15}/><span>White noise</span></Link></div></Panel>
 <Panel className="today-tasks"><div className="panel-header"><h2>Today’s Tasks</h2><Link href="/tasks" className="muted">{done}/{data.tasks.length}</Link></div><div className="dashboard-task-list">{tasks.map((task,i)=><div key={task.id} className={`dashboard-task ${task.done?'completed':''}`}><button className={`task-check ${task.done?'checked':''}`} aria-label={`${task.done?'Reopen':'Complete'} ${task.title}`} onClick={()=>update(d=>{const t=d.tasks.find(x=>x.id===task.id);if(t){t.done=!t.done;if(t.done&&t.recurrence!=='none'){const due=dateOffset(t.recurrence==='daily'?1:7,new Date((t.due||localDate())+'T12:00:00'));if(!d.tasks.some(x=>x.id!==t.id&&x.title===t.title&&x.due===due&&!x.done))d.tasks.push({...t,id:uid(),done:false,due,subtasks:t.subtasks.map(s=>({...s,id:uid(),done:false}))});}}})}>{task.done&&<Check size={12}/>}</button><Link href={`/tasks?task=${task.id}`}>{task.title}</Link><small>{data.events.find(e=>e.taskId===task.id)?.time||`${task.minutes} min`}</small><Link href={`/tasks?task=${task.id}`} className="task-more" aria-label={`Edit ${task.title}`}><MoreHorizontal size={14}/></Link></div>)}</div><Link href="/tasks?new=1" className="add-task-link"><Plus size={13}/>Add a little intention</Link></Panel></div>
 <div className="dashboard-bottom"><Panel className="analytics-card"><div className="panel-header"><h2>Study Analytics</h2><Link href="/analytics" className="mini-select">This week <ArrowUpRight size={11}/></Link></div><div className="analytics-stats"><div><strong>{duration(minutes)}</strong><span>Total focus time</span></div><div><strong>{weekSessions.length}</strong><span>Study sessions</span></div><div><strong>{focusRate}%</strong><span>Focus rate <i>↗</i></span></div></div><div className="bar-chart"><div className="chart-scale"><span>{Math.ceil(maxBar/60)}h</span><span>{Math.ceil(maxBar/120)}h</span><span>0h</span></div>{bars.map((bar,i)=><div className="bar-column" key={i}><div className="bar-track"><div className="chart-bar" style={{height:`${Math.max(3,bar.minutes/maxBar*100)}%`}} title={`${bar.day}: ${duration(bar.minutes)}`}/></div><span>{bar.day}</span></div>)}</div></Panel>
 <Panel className="subject-card"><div className="panel-header"><h2>Subject Progress</h2><Link href="/subjects" className="mini-select">All subjects <ArrowUpRight size={11}/></Link></div><div className="subject-progress-list">{data.subjects.map((s,i)=>{const Icon=subjectIcons[i%subjectIcons.length];const mastery=s.chapters.length?Math.round(s.chapters.reduce((a,c)=>a+c.mastery,0)/s.chapters.length):0;return <Link key={s.id} href={`/subjects?subject=${s.id}`} className="subject-progress"><span className="subject-icon" style={{color:s.color,background:`${s.color}20`}}><Icon size={18}/></span><span className="subject-name">{s.name}</span><Progress value={mastery} color={s.color}/><small>{mastery}%</small></Link>;})}</div></Panel></div>
 <Panel className="dashboard-intention"><div><span className="eyebrow">Your north star</span><h3>{goal?.title||'Make room for what matters.'}</h3><p className="muted">{goal?.vision||'Set your first intention and take one small step.'}</p></div><div className="intention-progress"><span>{goalProgress}% of the way</span><Progress value={goalProgress}/></div><Link href="/goals" className="icon-button" aria-label="Open goals"><ArrowUpRight size={20}/></Link></Panel>
 </div><aside className="dashboard-aside"><MiniCalendar/><Panel className="streak-card"><div><small>Current streak</small><strong>{streak} days</strong><span>Keep going.</span></div><span className="flame-orb"><Flame size={34} fill="#f49571" strokeWidth={1.4}/></span></Panel><Panel className="inspiration-card"><span className="quote-mark">“</span><p>Progress is quiet.<br/>But it changes everything.</p><span>—</span><span className="inspiration-orb"/></Panel><Link href="/calendar" className="next-event"><span className="eyebrow">On the horizon</span><strong>{data.events.filter(e=>e.date>today).sort((a,b)=>a.date.localeCompare(b.date))[0]?.title||'A little breathing room.'}</strong><span>Find your next moment <ArrowUpRight size={12}/></span></Link></aside></div>
 </div>;
}
function MiniCalendar(){
 const {data}=useStore();const [month,setMonth]=useState(()=>new Date());const today=localDate();
 const start=new Date(month.getFullYear(),month.getMonth(),1);const first=new Date(start);first.setDate(first.getDate()-first.getDay());
 const cells=Array.from({length:Math.ceil((start.getDay()+new Date(month.getFullYear(),month.getMonth()+1,0).getDate())/7)*7},(_,i)=>{const date=new Date(first);date.setDate(date.getDate()+i);return date;});
 return <Panel className="mini-calendar"><div className="panel-header"><h2>{month.toLocaleDateString('en-US',{month:'long',year:'numeric'})}</h2><div className="row"><button className="icon-button" aria-label="Previous month" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><ChevronLeft size={15}/></button><button className="icon-button" aria-label="Next month" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><ChevronRight size={15}/></button><button className="mini-select" onClick={()=>setMonth(new Date())}>Today</button></div></div><div className="calendar-weekdays">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=><span key={d}>{d}</span>)}</div><div className="calendar-days">{cells.map(date=>{const key=localDate(date);return <Link href={`/calendar?date=${key}`} key={key} className={`${date.getMonth()!==month.getMonth()?'outside':''} ${key===today?'today':''}`}><span>{date.getDate()}</span>{data.events.some(e=>e.date===key)&&<i/>}</Link>;})}</div></Panel>;
}


