'use client';

import { useEffect, useRef, useState } from 'react';
import { ArrowRight, ArrowUpRight, BookOpen, Check, CheckCircle2, ChevronRight, Circle, Clock3, FileText, Flag, GraduationCap, Layers3, Lightbulb, Link2, Pencil, Plus, Search, Sparkles, Star, Target, Trash2, TrendingUp } from 'lucide-react';
import { useStore } from '@/lib/store';
import { Button, Empty, Field, Modal, PageHeading, Panel, Progress } from '@/components/ui';
import type { Chapter, Goal, Grade, Note, Resource, Subject } from '@/lib/types';
import { average, dateOffset, duration, localDate, reviewChapter, safeUrl, uid } from '@/lib/utils';
import './learning.css';

const palette = ['#d59e79', '#b494bf', '#91ac9d', '#9babc9', '#d19aa8', '#b4ad80'];
const dateLabel = (value: string) => value ? new Date(`${value}T12:00:00`).toLocaleDateString('en-GB', { day: 'numeric', month: 'short' }) : 'Not scheduled';
const mastery = (subject: Subject) => subject.chapters.length ? Math.round(subject.chapters.reduce((sum, chapter) => sum + chapter.mastery, 0) / subject.chapters.length) : 0;
const mean = (values: number[]) => values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : 0;

function useDeepLink(key: string, apply: (value: string) => void) {
  const seen = useRef<string | null>(null);
  useEffect(() => {
    const value = new URLSearchParams(window.location.search).get(key);
    if (value !== seen.current) { seen.current = value; if (value) apply(value); }
  });
}

function SubjectSelect({ value, onChange, subjects, all = false }: { value: string; onChange: (value: string) => void; subjects: Subject[]; all?: boolean }) {
  return <select className="input" value={value} onChange={event => onChange(event.target.value)} aria-label="Subject"><option value="">{all ? 'All subjects' : 'General / no subject'}</option>{subjects.map(subject => <option key={subject.id} value={subject.id}>{subject.name}</option>)}</select>;
}

function SubjectTag({ subject }: { subject?: Subject }) {
  return <span className="learn-subject-tag"><i style={{ background: subject?.color || '#b7ac9e' }} />{subject?.name || 'Personal'}</span>;
}

function Metric({ label, value, detail, icon }: { label: string; value: React.ReactNode; detail: string; icon: React.ReactNode }) {
  return <Panel className="learn-metric"><div className="learn-metric-top"><span>{label}</span><span className="learn-icon">{icon}</span></div><div className="learn-metric-value">{value}</div><p>{detail}</p></Panel>;
}

export function SubjectsPage() {
  const { data, update, notify } = useStore();
  const [selectedId, setSelectedId] = useState(data.subjects[0]?.id || '');
  const [subjectEditor, setSubjectEditor] = useState<Subject | null>(null);
  const [chapterEditor, setChapterEditor] = useState<Chapter | null>(null);
  useDeepLink('subject', setSelectedId);
  const selected = data.subjects.find(subject => subject.id === selectedId) || data.subjects[0];
  const chapters = data.subjects.flatMap(subject => subject.chapters);
  const due = chapters.filter(chapter => !chapter.nextReview || chapter.nextReview <= localDate()).length;

  function saveSubject(event: React.FormEvent) {
    event.preventDefault();
    if (!subjectEditor?.name.trim()) return;
    update(draft => { const existing = draft.subjects.findIndex(subject => subject.id === subjectEditor.id); if (existing >= 0) draft.subjects[existing] = { ...subjectEditor, name: subjectEditor.name.trim() }; else draft.subjects.push({ ...subjectEditor, name: subjectEditor.name.trim() }); });
    setSelectedId(subjectEditor.id); setSubjectEditor(null); notify('Subject saved');
  }

  function saveChapter(event: React.FormEvent) {
    event.preventDefault();
    if (!chapterEditor?.title.trim() || !selected) return;
    update(draft => { const subject = draft.subjects.find(item => item.id === selected.id); if (!subject) return; const index = subject.chapters.findIndex(chapter => chapter.id === chapterEditor.id); const value = { ...chapterEditor, title: chapterEditor.title.trim() }; if (index >= 0) subject.chapters[index] = value; else subject.chapters.push(value); });
    setChapterEditor(null); notify('Chapter saved');
  }

  return <div className="page-stack learn-page">
    <PageHeading eyebrow="YOUR KNOWLEDGE, CONNECTED" title="A little more understanding." description="Build your knowledge, one meaningful connection at a time." actions={<Button variant="primary" onClick={() => setSubjectEditor({ id: uid(), name: '', color: palette[data.subjects.length % palette.length], icon: 'book', chapters: [] })}><Plus size={16} />New subject</Button>} />
    <div className="learn-stat-strip"><span><strong>{data.subjects.length}</strong> subjects in your orbit</span><span><strong>{chapters.length}</strong> chapters explored</span><span><strong>{Math.round(mean(chapters.map(chapter => chapter.mastery)))}%</strong> overall mastery</span><span><strong>{due}</strong> ready to revisit</span></div>
    <div className="learn-subject-grid">{data.subjects.map((subject, index) => <button type="button" key={subject.id} className={`learn-subject-card ${selected?.id === subject.id ? 'is-selected' : ''}`} style={{ '--subject-color': subject.color } as React.CSSProperties} onClick={() => setSelectedId(subject.id)}><div className="learn-subject-orbit" /><span className="learn-subject-number">0{index + 1}</span><span className="learn-subject-symbol"><BookOpen size={28} strokeWidth={1.3} /></span><h2>{subject.name}</h2><p>{subject.chapters.length} chapters · {subject.chapters.filter(chapter => chapter.mastery >= 80).length} mastered</p><div className="learn-subject-bottom"><span>Knowledge confidence</span><b>{mastery(subject)}%</b></div><Progress value={mastery(subject)} color={subject.color} /></button>)}</div>
    {!data.subjects.length && <Empty text="Your knowledge map starts with a subject. Add your first one above." />}
    {selected && <Panel><div className="panel-header"><div><span className="eyebrow">KNOWLEDGE MAP</span><h2>{selected.name}, chapter by chapter.</h2></div><div className="row"><Button variant="ghost" onClick={() => setSubjectEditor({ ...selected })}><Pencil size={14} />Edit subject</Button><Button variant="soft" onClick={() => setChapterEditor({ id: uid(), title: '', mastery: 0, lastReviewed: '', nextReview: localDate(), question: '', answer: '', exercise: '', solution: '', notes: '', errors: '' })}><Plus size={15} />Add chapter</Button></div></div>
      <div className="learn-chapter-grid">{selected.chapters.map((chapter, index) => <button type="button" className="learn-chapter" key={chapter.id} onClick={() => setChapterEditor({ ...chapter })}><span className={`learn-chapter-node ${chapter.mastery >= 80 ? 'is-complete' : ''}`} style={{ '--subject-color': selected.color } as React.CSSProperties}>{chapter.mastery >= 80 ? <Check size={18} /> : String(index + 1).padStart(2, '0')}</span><div className="learn-chapter-content"><div className="between"><h3>{chapter.title}</h3><Pencil size={14} /></div><p>{chapter.notes || 'Add a memory, a question, a connection.'}</p><div className="learn-chapter-meta"><span>{chapter.mastery}% confidence</span><span>{chapter.nextReview && chapter.nextReview <= localDate() ? 'Ready to review' : `Review ${dateLabel(chapter.nextReview)}`}</span></div><Progress value={chapter.mastery} color={selected.color} /></div></button>)}</div>
      {!selected.chapters.length && <Empty text="Add a chapter to start mapping what you know." />}
    </Panel>}
    <Modal open={Boolean(subjectEditor)} onClose={() => setSubjectEditor(null)} title={data.subjects.some(subject => subject.id === subjectEditor?.id) ? 'Edit subject' : 'A new area of curiosity'}>{subjectEditor && <form onSubmit={saveSubject} className="stack"><Field label="Subject name"><input className="input" required value={subjectEditor.name} onChange={event => setSubjectEditor({ ...subjectEditor, name: event.target.value })} placeholder="e.g. Mathematics" /></Field><Field label="Color"><div className="learn-color-options">{palette.map(color => <button type="button" key={color} aria-label={`Choose ${color}`} className={subjectEditor.color === color ? 'active' : ''} onClick={() => setSubjectEditor({ ...subjectEditor, color })} style={{ background: color }}>{subjectEditor.color === color && <Check size={18} />}</button>)}</div></Field><Button variant="primary" type="submit">Save subject</Button></form>}</Modal>
    <Modal open={Boolean(chapterEditor)} onClose={() => setChapterEditor(null)} title="Make the knowledge yours">{chapterEditor && <form onSubmit={saveChapter} className="stack"><Field label="Chapter title"><input className="input" required value={chapterEditor.title} onChange={event => setChapterEditor({ ...chapterEditor, title: event.target.value })} /></Field><div className="form-grid"><Field label={`Confidence · ${chapterEditor.mastery}%`}><input type="range" min="0" max="100" value={chapterEditor.mastery} onChange={event => setChapterEditor({ ...chapterEditor, mastery: Number(event.target.value) })} /></Field><Field label="Next review"><input type="date" className="input" value={chapterEditor.nextReview} onChange={event => setChapterEditor({ ...chapterEditor, nextReview: event.target.value })} /></Field></div><Field label="Active recall question"><textarea className="input" rows={2} value={chapterEditor.question} onChange={event => setChapterEditor({ ...chapterEditor, question: event.target.value })} placeholder="What should you be able to explain without looking?" /></Field><Field label="Reference answer"><textarea className="input" rows={3} value={chapterEditor.answer} onChange={event => setChapterEditor({ ...chapterEditor, answer: event.target.value })} /></Field><div className="form-grid"><Field label="Practice exercise"><textarea className="input" rows={3} value={chapterEditor.exercise || ''} onChange={event => setChapterEditor({ ...chapterEditor, exercise: event.target.value })} /></Field><Field label="Worked solution"><textarea className="input" rows={3} value={chapterEditor.solution || ''} onChange={event => setChapterEditor({ ...chapterEditor, solution: event.target.value })} /></Field></div><Field label="Your notes & connections"><textarea className="input" rows={3} value={chapterEditor.notes || ''} onChange={event => setChapterEditor({ ...chapterEditor, notes: event.target.value })} /></Field><Field label="Mistakes to learn from"><textarea className="input" rows={2} value={chapterEditor.errors || ''} onChange={event => setChapterEditor({ ...chapterEditor, errors: event.target.value })} /></Field><div className="between"><Button variant="ghost" type="button" onClick={() => { update(draft => { const subject = draft.subjects.find(item => item.id === selected?.id); if (subject) subject.chapters = subject.chapters.filter(chapter => chapter.id !== chapterEditor.id); }); setChapterEditor(null); notify('Chapter removed'); }}><Trash2 size={15} />Remove chapter</Button><Button variant="primary" type="submit">Save chapter</Button></div></form>}</Modal>
  </div>;
}

export function RevisionPage() {
  const { data, update, notify } = useStore();
  const [all, setAll] = useState(false);
  const [activeId, setActiveId] = useState('');
  const [answer, setAnswer] = useState('');
  const [revealed, setRevealed] = useState(false);
  const [exercise, setExercise] = useState(false);
  const [reviewed, setReviewed] = useState(0);
  const chapters = data.subjects.flatMap(subject => subject.chapters.map(chapter => ({ chapter, subject })));
  const due = chapters.filter(({ chapter }) => !chapter.nextReview || chapter.nextReview <= localDate());
  const queue = (all ? chapters : due).slice().sort((a, b) => a.chapter.nextReview.localeCompare(b.chapter.nextReview));
  const active = queue.find(({ chapter }) => chapter.id === activeId) || queue[0];
  function choose(id: string) { setActiveId(id); setAnswer(''); setRevealed(false); setExercise(false); }
  function rate(rating: number) {
    if (!active) return;
    const revised = reviewChapter(active.chapter, rating);
    update(draft => { const subject = draft.subjects.find(item => item.id === active.subject.id); if (subject) subject.chapters = subject.chapters.map(chapter => chapter.id === active.chapter.id ? revised : chapter); });
    setReviewed(value => value + 1); setAnswer(''); setRevealed(false); setExercise(false); setActiveId(queue.find(({ chapter }) => chapter.id !== active.chapter.id)?.chapter.id || ''); notify(`Review saved · next visit ${dateLabel(revised.nextReview)}`);
  }
  return <div className="page-stack learn-page"><PageHeading eyebrow="REMEMBER WHAT MATTERS" title="Let it become second nature." description="A little retrieval today. A stronger memory tomorrow." />
    <div className="learn-revision-layout"><aside className="learn-revision-side"><Panel className="learn-revision-summary"><span className="learn-icon learn-icon-large"><Layers3 size={25} strokeWidth={1.4} /></span><div className="learn-big-number">{due.length}<span>chapters ready</span></div><p>Space it out. Recall it deeply.<br />Make room for lasting knowledge.</p><div className="learn-session-count"><CheckCircle2 size={15} />{reviewed} reviewed this visit</div></Panel><Panel><div className="between"><h3>Your review queue</h3><span className="badge">{queue.length}</span></div><label className="learn-toggle"><input type="checkbox" checked={all} onChange={event => { setAll(event.target.checked); choose(''); }} />Include future reviews</label><div className="learn-review-queue">{queue.map(({ chapter, subject }) => <button className={`learn-queue-item ${active?.chapter.id === chapter.id ? 'active' : ''}`} key={chapter.id} onClick={() => choose(chapter.id)}><i style={{ background: subject.color }} /><div><b>{chapter.title}</b><span>{subject.name} · {chapter.mastery}%</span></div><ChevronRight size={14} /></button>)}</div>{!queue.length && <p className="muted">A clear queue. A little space to breathe.</p>}</Panel></aside>
      <Panel className="learn-recall-card">{active ? <><div className="between"><SubjectTag subject={active.subject} /><span className="badge">{exercise ? 'Practice' : 'Active recall'}</span></div><div className="learn-recall-question"><span className="eyebrow">{active.chapter.title}</span><h2>{exercise ? active.chapter.exercise : active.chapter.question || `What can you explain about ${active.chapter.title}?`}</h2><p className="muted">Take your time. Try recalling it before looking at the answer.</p></div><Field label="Your thinking"><textarea className="input learn-recall-input" rows={6} placeholder="Explain it in your own words…" value={answer} onChange={event => setAnswer(event.target.value)} /></Field>{!revealed ? <div className="learn-recall-actions"><Button variant="primary" onClick={() => setRevealed(true)}>Reveal {exercise ? 'solution' : 'answer'}<ArrowRight size={16} /></Button>{active.chapter.exercise && <Button variant="ghost" onClick={() => { setExercise(!exercise); setAnswer(''); }}>{exercise ? 'Back to recall' : 'Try an exercise'}</Button>}</div> : <><div className="learn-answer"><span className="eyebrow">{exercise ? 'WORKED SOLUTION' : 'REFERENCE ANSWER'}</span><p>{(exercise ? active.chapter.solution : active.chapter.answer) || 'No reference answer yet. Add one in Subjects to complete this card.'}</p>{active.chapter.errors && <div className="learn-error-reminder"><Lightbulb size={16} /><span>Remember: {active.chapter.errors}</span></div>}</div><div className="learn-self-rate"><h3>How well did you remember?</h3><p className="muted">Your rating adjusts confidence and schedules the next review.</p><div className="learn-rating-options">{[['Again', 'Tomorrow'], ['Hard', '2 days'], ['Good', '4 days'], ['Easy', '8 days']].map(([label, interval], index) => <button key={label} onClick={() => rate(index)} className={`learn-rating learn-rating-${index}`}><b>{label}</b><span>{interval}</span></button>)}</div></div></>}</> : <div className="learn-complete-state"><span className="learn-complete-orb"><Check size={34} strokeWidth={1.3} /></span><span className="eyebrow">A LITTLE MORE CONFIDENT</span><h2>You’re all caught up.</h2><p>Let your knowledge settle. Your next review will be here when it’s time.</p>{chapters.length > 0 && <Button variant="soft" onClick={() => setAll(true)}>Practice any chapter<ArrowRight size={15} /></Button>}</div>}</Panel>
    </div><p className="learn-footnote">A transparent rhythm: Again +1 day, Hard +2, Good +4, Easy +8. Ratings adjust your confidence, not your grades.</p>
  </div>;
}

export function AnalyticsPage() {
  const { data } = useStore();
  const [period, setPeriod] = useState(7);
  const days = Array.from({ length: period }, (_, index) => dateOffset(index - period + 1));
  const sessions = data.sessions.filter(session => session.date.slice(0, 10) >= days[0] && session.date.slice(0, 10) <= localDate());
  const minutes = sessions.reduce((sum, session) => sum + session.minutes, 0);
  const grades = data.grades.filter(grade => grade.date >= days[0] && grade.date <= localDate()).sort((a, b) => a.date.localeCompare(b.date));
  const daily = days.map(date => ({ date, value: sessions.filter(session => session.date.slice(0, 10) === date).reduce((sum, session) => sum + session.minutes, 0) }));
  const maxMinutes = Math.max(60, ...daily.map(day => day.value));
  const completed = data.tasks.filter(task => task.done).length;
  const completion = data.tasks.length ? Math.round(completed / data.tasks.length * 100) : 0;
  const subjectMinutes = [...data.subjects.map(subject => ({ name: subject.name, color: subject.color, minutes: sessions.filter(session => data.tasks.find(task => task.id === session.taskId)?.subjectId === subject.id).reduce((sum, session) => sum + session.minutes, 0) })), { name: 'General focus', color: '#c3b9ae', minutes: sessions.filter(session => !data.subjects.some(subject => subject.id === data.tasks.find(task => task.id === session.taskId)?.subjectId)).reduce((sum, session) => sum + session.minutes, 0) }].filter(subject => subject.minutes > 0).sort((a, b) => b.minutes - a.minutes);
  const points = grades.map((grade, index) => `${grades.length === 1 ? 250 : 28 + index * 444 / (grades.length - 1)},${170 - grade.score / grade.outOf * 140}`).join(' ');
  const sessionDays = new Set(data.sessions.filter(session => session.minutes > 0).map(session => session.date.slice(0, 10)));
  let streak = 0; const start = sessionDays.has(localDate()) ? 0 : -1;
  for (let index = start; index > -367; index--) { if (sessionDays.has(dateOffset(index))) streak++; else break; }

  return <div className="page-stack learn-page"><PageHeading eyebrow="THE QUIET POWER OF CONSISTENCY" title="See how far you’ve come." description="A clear view of your effort, your rhythm, and your progress." actions={<div className="learn-segmented">{[7, 30].map(value => <button className={period === value ? 'active' : ''} key={value} onClick={() => setPeriod(value)}>Last {value} days</button>)}</div>} />
    <div className="learn-metric-grid"><Metric label="Time, well spent" value={duration(minutes)} detail={`${sessions.length} focus sessions in this period`} icon={<Clock3 size={18} />} /><Metric label="A steady rhythm" value={<>{streak}<small> days</small></>} detail="Current streak of completed focus sessions" icon={<Sparkles size={18} />} /><Metric label="Tasks completed" value={<>{completion}<small>%</small></>} detail={`${completed} of ${data.tasks.length} tasks · all time`} icon={<CheckCircle2 size={18} />} /><Metric label="Weighted average" value={grades.length ? <>{average(grades).toFixed(1)}<small> / 20</small></> : '—'} detail={`${grades.length} assessments in this period`} icon={<GraduationCap size={18} />} /></div>
    <div className="learn-analytics-grid"><Panel className="learn-focus-chart"><div className="panel-header"><div><span className="eyebrow">DEEP WORK</span><h2>Your focus has a rhythm.</h2></div><span className="badge"><i className="learn-dot" />Focus minutes</span></div><div className="learn-bars" style={{ '--bar-count': period } as React.CSSProperties}><div className="learn-chart-grid"><span>{maxMinutes}m</span><span>{Math.round(maxMinutes / 2)}m</span><span>0</span></div>{daily.map((day, index) => <div className="learn-bar-column" key={day.date}><div className="learn-bar-track"><div tabIndex={0} role="img" aria-label={`${dateLabel(day.date)}: ${day.value} focus minutes`} className={`learn-bar ${index === daily.length - 1 ? 'today' : ''}`} style={{ height: `${day.value / maxMinutes * 100}%`, minHeight: day.value ? 4 : 2 }}><span>{dateLabel(day.date)} · {duration(day.value)}</span></div></div><span className="learn-axis-label">{period === 7 ? new Date(`${day.date}T12:00:00`).toLocaleDateString('en-US', { weekday: 'short' }) : (index % 5 === 0 || index === period - 1) ? dateLabel(day.date) : ''}</span></div>)}</div><div className="learn-chart-bottom"><span>{dateLabel(days[0])} — {dateLabel(localDate())}</span><b>{duration(minutes / period)} daily average</b></div></Panel>
      <Panel><span className="eyebrow">WHERE YOUR ATTENTION GOES</span><h2>A balanced orbit.</h2><div className="learn-focus-orbit"><div className="learn-donut" style={{ background: minutes ? `conic-gradient(${subjectMinutes.map((subject, index) => `${subject.color} ${subjectMinutes.slice(0, index).reduce((sum, value) => sum + value.minutes, 0) / minutes * 100}% ${subjectMinutes.slice(0, index + 1).reduce((sum, value) => sum + value.minutes, 0) / minutes * 100}%`).join(',')})` : '#e5e0dc' }}><div><b>{(minutes / 60).toFixed(1)}</b><span>focused hours</span></div></div></div><div className="learn-distribution">{subjectMinutes.map(subject => <div className="between" key={subject.name}><span><i style={{ background: subject.color }} />{subject.name}</span><b>{duration(subject.minutes)}</b></div>)}</div>{!subjectMinutes.length && <p className="muted">Complete a focus session to see your distribution.</p>}</Panel>
    </div><div className="grid-2"><Panel><div className="panel-header"><div><span className="eyebrow">ASSESSMENT JOURNEY</span><h2>Progress, in perspective.</h2></div><TrendingUp size={22} strokeWidth={1.4} /></div>{grades.length ? <><svg className="learn-line-chart" viewBox="0 0 500 200" role="img" aria-label={`Grades over the selected period: ${grades.map(grade => `${grade.title}, ${(grade.score / grade.outOf * 20).toFixed(1)} out of 20`).join('; ')}`}><defs><linearGradient id="grade-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#d8af98" stopOpacity=".32" /><stop offset="1" stopColor="#d8af98" stopOpacity="0" /></linearGradient></defs>{[30, 65, 100, 135, 170].map((y, index) => <g key={y}><line x1="28" y1={y} x2="472" y2={y} stroke="#ddd6ce" strokeDasharray="3 5" /><text x="5" y={y + 4} fontSize="10" fill="#a2978d">{20 - index * 5}</text></g>)}<polygon points={`28,170 ${points} 472,170`} fill="url(#grade-fill)" /><polyline points={points} fill="none" stroke="#c28c75" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />{grades.map((grade, index) => <circle key={grade.id} cx={grades.length === 1 ? 250 : 28 + index * 444 / (grades.length - 1)} cy={170 - grade.score / grade.outOf * 140} r="4" fill="#fffaf5" stroke="#c28c75" strokeWidth="2"><title>{grade.title}: {(grade.score / grade.outOf * 20).toFixed(1)}/20</title></circle>)}</svg><div className="learn-chart-bottom"><span>{dateLabel(grades[0].date)}</span><span>Normalized to /20 · ordered by date</span><span>{dateLabel(grades[grades.length - 1].date)}</span></div></> : <Empty text="Add an assessment in Grades to see your progress here." />}</Panel>
      <Panel><span className="eyebrow">KNOWLEDGE CONFIDENCE</span><h2>Growing, subject by subject.</h2><div className="learn-mastery-list">{data.subjects.map(subject => <div key={subject.id}><div className="between"><SubjectTag subject={subject} /><b>{mastery(subject)}%</b></div><Progress value={mastery(subject)} color={subject.color} /></div>)}</div><p className="learn-footnote">Confidence comes from chapter ratings and your self-assessment.</p></Panel></div>
  </div>;
}

export function GradesPage() {
  const { data, update, notify } = useStore();
  const [editor, setEditor] = useState<Grade | null>(null);
  const [errors, setErrors] = useState('');
  const [subjectId, setSubjectId] = useState('');
  const grades = data.grades.filter(grade => !subjectId || grade.subjectId === subjectId).slice().sort((a, b) => b.date.localeCompare(a.date));
  const open = (grade?: Grade) => { setEditor(grade ? { ...grade } : { id: uid(), title: '', subjectId: data.subjects[0]?.id || '', score: 0, outOf: 20, coefficient: 1, date: localDate(), errors: [], chapter: '' }); setErrors(grade?.errors.join(', ') || ''); };
  function save(event: React.FormEvent) { event.preventDefault(); if (!editor || !editor.title.trim() || editor.outOf <= 0 || editor.coefficient <= 0 || editor.score < 0 || editor.score > editor.outOf) return; const grade = { ...editor, title: editor.title.trim(), errors: errors.split(',').map(error => error.trim()).filter(Boolean) }; update(draft => { const index = draft.grades.findIndex(item => item.id === grade.id); if (index >= 0) draft.grades[index] = grade; else draft.grades.push(grade); }); setEditor(null); notify('Assessment saved'); }
  const errorCounts = data.grades.flatMap(grade => grade.errors).reduce<Record<string, number>>((result, error) => { result[error] = (result[error] || 0) + 1; return result; }, {});
  function makePractice(grade: Grade) { const title = `Review: ${grade.title}`; if (data.tasks.some(task => task.title === title && !task.done)) { notify('This review is already in your inbox'); return; } update(draft => { draft.tasks.push({ id: uid(), title, subjectId: grade.subjectId, quadrant: 'inbox', done: false, due: dateOffset(1), minutes: 25, difficulty: 2, energy: 'medium', notes: `After-assessment review.\n${grade.errors.map(error => `• ${error}`).join('\n')}\n${grade.chapter || ''}`, subtasks: [], recurrence: 'none' }); }); notify('Review task added to your inbox'); }

  return <div className="page-stack learn-page"><PageHeading eyebrow="EVERY RESULT IS INFORMATION" title="More than a number." description="Track your results. Understand the patterns. Grow from what you learn." actions={<Button variant="primary" onClick={() => open()}><Plus size={16} />Add assessment</Button>} />
    <div className="learn-grade-overview"><Panel className="learn-grade-hero"><span className="eyebrow">YOUR WEIGHTED AVERAGE</span><div className="learn-grade-average">{data.grades.length ? average(data.grades).toFixed(1) : '—'}<span>/ 20</span></div><p>{data.grades.length} assessments, each part of the story.</p><div className="learn-grade-decoration"><GraduationCap size={75} strokeWidth={.8} /></div></Panel><Panel><span className="eyebrow">THE VIEW BY SUBJECT</span><div className="learn-grade-subjects">{data.subjects.map(subject => { const values = data.grades.filter(grade => grade.subjectId === subject.id); return <div key={subject.id} className="between"><SubjectTag subject={subject} /><span><b>{values.length ? average(values).toFixed(1) : '—'}</b><small> / 20</small><span className="learn-small-count">{values.length} results</span></span></div>; })}</div></Panel></div>
    <Panel><div className="panel-header"><div><span className="eyebrow">ASSESSMENT JOURNAL</span><h2>Small lessons. Lasting progress.</h2></div><SubjectSelect value={subjectId} onChange={setSubjectId} subjects={data.subjects} all /></div><div className="learn-table-wrap"><table className="learn-table"><thead><tr><th>Assessment</th><th>Subject</th><th>Result</th><th>Weight</th><th>Date</th><th><span className="learn-sr-only">Actions</span></th></tr></thead><tbody>{grades.map(grade => <tr key={grade.id}><td><button className="learn-text-button learn-assessment-title" onClick={() => open(grade)}>{grade.title}</button>{Boolean(grade.errors.length) && <div className="learn-error-tags">{grade.errors.map((error, index) => <span key={`${error}-${index}`}>{error}</span>)}</div>}</td><td><SubjectTag subject={data.subjects.find(subject => subject.id === grade.subjectId)} /></td><td><span className={`learn-grade-pill ${grade.score / grade.outOf >= .75 ? 'high' : ''}`}><b>{grade.score}</b> / {grade.outOf}</span></td><td>×{grade.coefficient}</td><td>{dateLabel(grade.date)}</td><td><div className="row"><button className="icon-button" aria-label={`Create review task for ${grade.title}`} title="Create a review task" onClick={() => makePractice(grade)}><BookOpen size={15} /></button><button className="icon-button" aria-label={`Edit ${grade.title}`} onClick={() => open(grade)}><Pencil size={15} /></button><button className="icon-button" aria-label={`Delete ${grade.title}`} onClick={() => { update(draft => { draft.grades = draft.grades.filter(item => item.id !== grade.id); }); notify('Assessment removed'); }}><Trash2 size={15} /></button></div></td></tr>)}</tbody></table></div>{!grades.length && <Empty text="No assessments here yet. Add a result to start your journal." />}</Panel>
    <Panel className="learn-pattern-card"><span className="learn-icon learn-icon-large"><Lightbulb size={24} strokeWidth={1.4} /></span><div><span className="eyebrow">MISTAKES ARE USEFUL CLUES</span><h2>Your learning patterns.</h2>{Object.keys(errorCounts).length ? <div className="learn-error-patterns">{Object.entries(errorCounts).sort((a, b) => b[1] - a[1]).map(([error, count]) => <span className="badge" key={error}>{error}<b>×{count}</b></span>)}</div> : <p className="muted">Tag the things that tripped you up after an assessment. Patterns will become visible here.</p>}</div></Panel>
    <Modal open={Boolean(editor)} onClose={() => setEditor(null)} title={data.grades.some(grade => grade.id === editor?.id) ? 'Edit assessment' : 'A new point of progress'}>{editor && <form className="stack" onSubmit={save}><Field label="Assessment title"><input className="input" value={editor.title} required onChange={event => setEditor({ ...editor, title: event.target.value })} placeholder="e.g. Calculus — midterm" /></Field><Field label="Subject"><SubjectSelect subjects={data.subjects} value={editor.subjectId} onChange={value => setEditor({ ...editor, subjectId: value })} /></Field><div className="learn-three-fields"><Field label="Score"><input className="input" type="number" min="0" max={editor.outOf} step="0.01" required value={editor.score} onChange={event => setEditor({ ...editor, score: Number(event.target.value) })} /></Field><Field label="Out of"><input className="input" type="number" min="0.01" step="0.01" required value={editor.outOf} onChange={event => setEditor({ ...editor, outOf: Number(event.target.value) })} /></Field><Field label="Coefficient"><input className="input" type="number" min="0.01" step="0.01" required value={editor.coefficient} onChange={event => setEditor({ ...editor, coefficient: Number(event.target.value) })} /></Field></div><Field label="Assessment date"><input className="input" type="date" required value={editor.date} onChange={event => setEditor({ ...editor, date: event.target.value })} /></Field><Field label="Chapter or topic"><input className="input" value={editor.chapter || ''} onChange={event => setEditor({ ...editor, chapter: event.target.value })} /></Field><Field label="What to learn from · separate with commas"><textarea className="input" rows={3} value={errors} onChange={event => setErrors(event.target.value)} placeholder="Time management, Sign errors, Definitions" /></Field><p className="learn-footnote">Your average converts every score to /20 and weights it by its coefficient.</p><Button variant="primary" type="submit">Save assessment</Button></form>}</Modal>
  </div>;
}

export function GoalsPage() {
  const { data, update, notify } = useStore();
  const [editor, setEditor] = useState<Goal | null>(null);
  const [milestones, setMilestones] = useState('');
  const completed = data.goals.filter(goal => goal.milestones.length > 0 && goal.milestones.every(milestone => milestone.done)).length;
  function open(goal?: Goal) { setEditor(goal ? { ...goal } : { id: uid(), title: '', vision: '', due: dateOffset(30), milestones: [] }); setMilestones(goal?.milestones.map(milestone => milestone.title).join('\n') || ''); }
  function save(event: React.FormEvent) { event.preventDefault(); if (!editor?.title.trim()) return; const goal = { ...editor, title: editor.title.trim(), milestones: [...new Set(milestones.split('\n').map(title => title.trim()).filter(Boolean))].map(title => { const existing = editor.milestones.find(milestone => milestone.title === title); return existing || { id: uid(), title, done: false }; }) }; update(draft => { const index = draft.goals.findIndex(item => item.id === goal.id); if (index >= 0) draft.goals[index] = goal; else draft.goals.push(goal); }); setEditor(null); notify('Goal saved'); }
  function createAction(goal: Goal) { const milestone = goal.milestones.find(item => !item.done); const title = milestone?.title || goal.title; const marker = `Goal: ${goal.id}${milestone ? ` / ${milestone.id}` : ''}`; if (data.tasks.some(task => task.notes.includes(marker) && !task.done)) { notify('This next action is already in your inbox'); return; } update(draft => { draft.tasks.push({ id: uid(), title, subjectId: '', quadrant: 'inbox', done: false, due: goal.due || dateOffset(1), minutes: 30, difficulty: 2, energy: 'medium', notes: `${marker}\n${goal.title}\n${goal.vision}`, subtasks: [], recurrence: 'none' }); }); notify('Next action added to your inbox'); }
  return <div className="page-stack learn-page"><PageHeading eyebrow="A DIRECTION THAT FEELS LIKE YOU" title="Make space for your ambitions." description="Connect the big picture to the next small step." actions={<Button variant="primary" onClick={() => open()}><Plus size={16} />New goal</Button>} />
    <Panel className="learn-goal-banner"><div><span className="eyebrow">YOUR NORTH STAR</span><h2>Think in possibilities.<br /><em>Move in small steps.</em></h2><p>{data.goals.length - completed} goals in motion · {completed} completed</p></div><div className="learn-goal-orbit"><div /><div /><div /><Star size={39} strokeWidth={1.1} /></div></Panel>
    <div className="grid-2">{data.goals.map((goal, index) => { const done = goal.milestones.filter(milestone => milestone.done).length; const progress = goal.milestones.length ? done / goal.milestones.length * 100 : 0; return <Panel className="learn-goal-card" key={goal.id}><div className="between"><span className="learn-icon" style={{ background: `${palette[index % palette.length]}24`, color: palette[index % palette.length] }}><Flag size={19} /></span><div className="row"><span className="badge">{dateLabel(goal.due)}</span><button className="icon-button" aria-label={`Edit ${goal.title}`} onClick={() => open(goal)}><Pencil size={14} /></button><button className="icon-button" aria-label={`Delete ${goal.title}`} onClick={() => { update(draft => { draft.goals = draft.goals.filter(item => item.id !== goal.id); }); notify('Goal removed'); }}><Trash2 size={14} /></button></div></div><h2>{goal.title}</h2><p className="learn-goal-vision">{goal.vision || 'Every meaningful journey starts with a direction.'}</p><div className="between learn-goal-progress-label"><span>{done} of {goal.milestones.length} milestones</span><b>{Math.round(progress)}%</b></div><Progress value={progress} color={palette[index % palette.length]} /><div className="learn-milestones">{goal.milestones.map(milestone => <label key={milestone.id} className={milestone.done ? 'is-done' : ''}><input type="checkbox" checked={milestone.done} onChange={() => update(draft => { const value = draft.goals.find(item => item.id === goal.id)?.milestones.find(item => item.id === milestone.id); if (value) value.done = !value.done; })} /><span>{milestone.title}</span></label>)}</div><Button variant="soft" disabled={progress === 100} onClick={() => createAction(goal)}>{progress === 100 ? <><Check size={15} />A goal well earned</> : <>Turn the next step into a task<ArrowUpRight size={15} /></>}</Button></Panel>; })}</div>{!data.goals.length && <Empty text="What would you love to work toward? Create your first goal." />}
    <Modal open={Boolean(editor)} onClose={() => setEditor(null)} title="Give your ambition a direction">{editor && <form className="stack" onSubmit={save}><Field label="Goal"><input className="input" required value={editor.title} onChange={event => setEditor({ ...editor, title: event.target.value })} placeholder="What do you want to make possible?" /></Field><Field label="Why it matters"><textarea className="input" rows={3} value={editor.vision} onChange={event => setEditor({ ...editor, vision: event.target.value })} placeholder="The reason behind your goal…" /></Field><Field label="Target date"><input className="input" type="date" value={editor.due} onChange={event => setEditor({ ...editor, due: event.target.value })} /></Field><Field label="Milestones · one small step per line"><textarea className="input" rows={6} value={milestones} onChange={event => setMilestones(event.target.value)} placeholder={'Map the starting point\nPractice the fundamentals\nComplete a first attempt'} /></Field><Button variant="primary" type="submit">Save goal</Button></form>}</Modal>
  </div>;
}

export function NotesPage() {
  const { data, update, notify } = useStore();
  const [query, setQuery] = useState('');
  const [subjectId, setSubjectId] = useState('');
  const [editor, setEditor] = useState<Note | null>(data.notes[0] ? { ...data.notes[0], links: [...data.notes[0].links] } : null);
  const [map, setMap] = useState(false);
  const [dirty, setDirty] = useState(false);
  const [pending, setPending] = useState<Note | null>(null);
  const notes = data.notes.filter(note => (!subjectId || note.subjectId === subjectId) && `${note.title} ${note.body}`.toLowerCase().includes(query.toLowerCase())).slice().sort((a, b) => b.updatedAt.localeCompare(a.updatedAt));
  function change(patch: Partial<Note>) { if (editor) { setEditor({ ...editor, ...patch }); setDirty(true); } }
  function select(note: Note) { if (dirty) { setPending(note); return; } setEditor({ ...note, links: [...note.links] }); setDirty(false); }
  useDeepLink('note', value => { const note = data.notes.find(item => item.id === value); if (note) select(note); });
  function newNote() { select({ id: uid(), title: '', body: '', subjectId: subjectId, kind: 'Idea', updatedAt: new Date().toISOString(), links: [] }); }
  function save() { if (!editor?.title.trim()) { notify('Give your note a title first'); return false; } const wikiTitles = [...editor.body.matchAll(/\[\[([^\]]+)\]\]/g)].map(match => match[1].trim().toLowerCase()); const note = { ...editor, title: editor.title.trim(), updatedAt: new Date().toISOString(), links: [...new Set([...editor.links, ...data.notes.filter(item => item.id !== editor.id && wikiTitles.includes(item.title.toLowerCase())).map(item => item.id)])] }; update(draft => { const index = draft.notes.findIndex(item => item.id === note.id); if (index >= 0) draft.notes[index] = note; else draft.notes.push(note); }); setEditor(note); setDirty(false); notify('Note saved'); return true; }
  const linked = data.notes.filter(note => editor?.links.includes(note.id) || note.links.includes(editor?.id || ''));
  const constellation = data.notes.slice(0, 18).map((note, index, list) => ({ note, x: 300 + Math.cos(index / list.length * Math.PI * 2 - Math.PI / 2) * (index % 2 ? 160 : 210), y: 155 + Math.sin(index / list.length * Math.PI * 2 - Math.PI / 2) * (index % 2 ? 83 : 113) }));

  return <div className="page-stack learn-page"><PageHeading eyebrow="A HOME FOR YOUR THINKING" title="Your mind, with more room." description="Capture an idea. Follow a connection. Let your second brain grow." actions={<><Button variant="ghost" onClick={() => setMap(!map)}><Sparkles size={16} />{map ? 'Hide connections' : 'See connections'}</Button><Button variant="primary" onClick={newNote}><Plus size={16} />New note</Button></>} />
    {map && <Panel className="learn-note-map"><div><span className="eyebrow">YOUR CONSTELLATION</span><h2>Ideas are better connected.</h2><p className="muted">Select a thought to explore. Lines show saved links.</p></div><svg viewBox="0 0 600 320" role="group" aria-label="Connected notes map">{constellation.flatMap(point => point.note.links.map(id => { const target = constellation.find(item => item.note.id === id); return target ? <line key={`${point.note.id}-${id}`} x1={point.x} y1={point.y} x2={target.x} y2={target.y} stroke="#cbb6c4" strokeWidth="1" /> : null; }))}{constellation.map(point => <g key={point.note.id} role="button" tabIndex={0} aria-label={`Open ${point.note.title}`} onClick={() => select(point.note)} onKeyDown={event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); select(point.note); } }}><circle cx={point.x} cy={point.y} r={point.note.id === editor?.id ? 14 : 10} fill={data.subjects.find(subject => subject.id === point.note.subjectId)?.color || '#bba7ba'} fillOpacity=".7" stroke="#fff" strokeWidth="3" /><text x={point.x} y={point.y + 27} textAnchor="middle" fontSize="10" fill="#665b5a">{point.note.title.length > 23 ? `${point.note.title.slice(0, 22)}…` : point.note.title}</text></g>)}</svg>{!data.notes.length && <Empty text="Your notes will form a constellation here." />}</Panel>}
    <div className="learn-notes-layout"><Panel className="learn-note-sidebar"><div className="learn-search"><Search size={16} /><input aria-label="Search notes" value={query} onChange={event => setQuery(event.target.value)} placeholder="Find a thought…" /></div><SubjectSelect value={subjectId} onChange={setSubjectId} subjects={data.subjects} all /><div className="learn-note-list">{notes.map(note => <button className={`learn-note-item ${editor?.id === note.id ? 'active' : ''}`} key={note.id} onClick={() => select(note)}><div className="between"><span className="learn-note-kind">{note.kind}</span><span>{dateLabel(note.updatedAt.slice(0, 10))}</span></div><h3>{note.title}</h3><p>{note.body || 'A thought waiting to take shape…'}</p><SubjectTag subject={data.subjects.find(subject => subject.id === note.subjectId)} /></button>)}</div>{!notes.length && <Empty text="No notes match this view." />}</Panel>
      <Panel className="learn-note-editor">{editor ? <><div className="between"><span className="eyebrow">{dirty ? 'UNSAVED THOUGHTS' : 'YOUR SECOND BRAIN'}</span><div className="row"><button className="icon-button" aria-label="Delete this note" onClick={() => { update(draft => { draft.notes = draft.notes.filter(note => note.id !== editor.id); draft.notes.forEach(note => { note.links = note.links.filter(id => id !== editor.id); }); }); setEditor(null); setDirty(false); notify('Note removed'); }}><Trash2 size={16} /></button><Button variant="primary" onClick={save}><Check size={15} />Save note</Button></div></div><input className="learn-note-title" aria-label="Note title" value={editor.title} onChange={event => change({ title: event.target.value })} placeholder="An idea worth keeping…" /><div className="learn-note-properties"><SubjectSelect subjects={data.subjects} value={editor.subjectId} onChange={value => change({ subjectId: value })} /><select className="input" aria-label="Note type" value={editor.kind} onChange={event => change({ kind: event.target.value })}>{[...new Set(['Idea', 'Course', 'Lecture', 'Formula', 'Summary', 'Reflection', 'Question', ...data.notes.map(note => note.kind)])].map(kind => <option key={kind}>{kind}</option>)}</select></div><textarea className="learn-note-body" aria-label="Note body" value={editor.body} onChange={event => change({ body: event.target.value })} placeholder={'Let your thinking flow.\n\nUse [[another note title]] to create a connection when you save.'} /><div className="learn-note-relations"><div className="between"><h3><Link2 size={15} />Connected thoughts</h3><span className="muted">{linked.length} connections</span></div>{linked.length > 0 && <div className="learn-linked-notes">{linked.map(note => <button key={note.id} onClick={() => select(note)}><FileText size={13} />{note.title}<ArrowUpRight size={12} /></button>)}</div>}<details><summary>Link another note</summary><div className="learn-link-choices">{data.notes.filter(note => note.id !== editor.id).map(note => <label key={note.id}><input type="checkbox" checked={editor.links.includes(note.id)} onChange={event => change({ links: event.target.checked ? [...editor.links, note.id] : editor.links.filter(id => id !== note.id) })} />{note.title}</label>)}</div>{data.notes.filter(note => note.id !== editor.id).length === 0 && <p className="muted">Create another note to start connecting your ideas.</p>}</details></div></> : <div className="learn-complete-state"><span className="learn-complete-orb"><FileText size={30} strokeWidth={1.2} /></span><h2>Make room for a thought.</h2><p>Select a note, or begin with a blank page.</p><Button variant="soft" onClick={newNote}><Plus size={15} />Create a note</Button></div>}</Panel>
    </div><Modal open={Boolean(pending)} onClose={() => setPending(null)} title="Keep your latest thoughts?"><p className="muted">This note has unsaved changes.</p><div className="learn-pending-actions"><Button variant="ghost" onClick={() => { setEditor(pending); setPending(null); setDirty(false); }}>Discard changes</Button><Button variant="primary" onClick={() => { if (save()) { setEditor(pending); setPending(null); setDirty(false); } }}>Save & continue</Button></div></Modal>
  </div>;
}

export function LibraryPage() {
  const { data, update, notify } = useStore();
  const [query, setQuery] = useState('');
  const [subjectId, setSubjectId] = useState('');
  const [kind, setKind] = useState('All');
  const [starred, setStarred] = useState(false);
  const [editor, setEditor] = useState<Resource | null>(null);
  const [error, setError] = useState('');
  useDeepLink('q', setQuery);
  const kinds = ['All', ...new Set(['Article', 'Video', 'Book', 'Course', 'Tool', ...data.resources.map(resource => resource.kind)])];
  const resources = data.resources.filter(resource => (!subjectId || resource.subjectId === subjectId) && (kind === 'All' || resource.kind === kind) && (!starred || resource.starred) && `${resource.title} ${resource.url}`.toLowerCase().includes(query.toLowerCase()));
  function save(event: React.FormEvent) { event.preventDefault(); if (!editor?.title.trim()) return; const url = safeUrl(editor.url); if (!url) { setError('Use a complete link starting with https:// or http://.'); return; } const value = { ...editor, title: editor.title.trim(), url }; update(draft => { const index = draft.resources.findIndex(resource => resource.id === editor.id); if (index >= 0) draft.resources[index] = value; else draft.resources.push(value); }); setEditor(null); notify('Resource saved to your library'); }
  return <div className="page-stack learn-page"><PageHeading eyebrow="COLLECT WHAT SPARKS SOMETHING" title="A library of possibilities." description="Good resources, kept close. Less searching. More discovering." actions={<Button variant="primary" onClick={() => { setError(''); setEditor({ id: uid(), title: '', url: '', kind: 'Article', subjectId: '', starred: false }); }}><Plus size={16} />Add resource</Button>} />
    <Panel className="learn-library-toolbar"><div className="learn-search"><Search size={16} /><input aria-label="Search resources" placeholder="Search your collection…" value={query} onChange={event => setQuery(event.target.value)} /></div><SubjectSelect value={subjectId} onChange={setSubjectId} subjects={data.subjects} all /><Button variant={starred ? 'primary' : 'ghost'} onClick={() => setStarred(!starred)}><Star size={15} fill={starred ? 'currentColor' : 'none'} />Favorites</Button></Panel><div className="learn-filter-tabs">{kinds.map(value => <button key={value} className={kind === value ? 'active' : ''} onClick={() => setKind(value)}>{value}<span>{value === 'All' ? data.resources.length : data.resources.filter(resource => resource.kind === value).length}</span></button>)}</div>
    <div className="learn-resource-grid">{resources.map((resource, index) => { const url = safeUrl(resource.url); let domain = ''; try { domain = new URL(url).hostname.replace(/^www\./, ''); } catch { domain = 'Invalid link'; } return <Panel key={resource.id} className="learn-resource-card"><div className={`learn-resource-art learn-resource-art-${index % 4}`}><span className="learn-resource-art-orbit" /><span className="learn-resource-type">{resource.kind}</span><BookOpen size={42} strokeWidth={.9} /><button className={`learn-resource-star ${resource.starred ? 'is-starred' : ''}`} aria-label={`${resource.starred ? 'Unfavorite' : 'Favorite'} ${resource.title}`} onClick={() => update(draft => { const item = draft.resources.find(value => value.id === resource.id); if (item) item.starred = !item.starred; })}><Star size={17} fill={resource.starred ? 'currentColor' : 'none'} /></button></div><div className="learn-resource-info"><SubjectTag subject={data.subjects.find(subject => subject.id === resource.subjectId)} /><h2>{resource.title}</h2><p><Link2 size={12} />{domain}</p><div className="between">{url ? <a className="learn-resource-open" href={url} target="_blank" rel="noopener noreferrer">Open resource<ArrowUpRight size={15} /></a> : <span className="muted">Edit to repair this link</span>}<div className="row"><button className="icon-button" aria-label={`Edit ${resource.title}`} onClick={() => { setError(''); setEditor({ ...resource }); }}><Pencil size={14} /></button><button className="icon-button" aria-label={`Remove ${resource.title}`} onClick={() => { update(draft => { draft.resources = draft.resources.filter(item => item.id !== resource.id); }); notify('Resource removed'); }}><Trash2 size={14} /></button></div></div></div></Panel>; })}</div>{!resources.length && <Empty text="No resources match this view. Save something that sparks your curiosity." />}
    <Modal open={Boolean(editor)} onClose={() => setEditor(null)} title="Keep a good resource close">{editor && <form className="stack" onSubmit={save}><Field label="Resource title"><input className="input" required value={editor.title} onChange={event => setEditor({ ...editor, title: event.target.value })} /></Field><Field label="Link"><input className="input" type="url" required value={editor.url} onChange={event => { setError(''); setEditor({ ...editor, url: event.target.value }); }} placeholder="https://…" /></Field>{error && <p className="learn-form-error" role="alert">{error}</p>}<div className="form-grid"><Field label="Resource type"><select className="input" value={editor.kind} onChange={event => setEditor({ ...editor, kind: event.target.value })}>{kinds.filter(value => value !== 'All').map(value => <option key={value}>{value}</option>)}</select></Field><Field label="Subject"><SubjectSelect value={editor.subjectId} onChange={value => setEditor({ ...editor, subjectId: value })} subjects={data.subjects} /></Field></div><label className="learn-toggle"><input type="checkbox" checked={editor.starred} onChange={event => setEditor({ ...editor, starred: event.target.checked })} />Keep in favorites</label><Button variant="primary" type="submit">Save resource</Button></form>}</Modal>
  </div>;
}

export function StrategyPage() {
  const { data, update, notify } = useStore();
  const startDate = dateOffset(-6);
  const latest = data.reviews.find(review => review.date >= startDate && review.date <= localDate());
  const [wins, setWins] = useState(latest?.wins || '');
  const [challenges, setChallenges] = useState(latest?.challenges || '');
  const [nextWeek, setNextWeek] = useState(latest?.nextWeek || '');
  const sessions = data.sessions.filter(session => session.date.slice(0, 10) >= startDate && session.date.slice(0, 10) <= localDate());
  const minutes = sessions.reduce((sum, session) => sum + session.minutes, 0);
  const relevantTasks = data.tasks.filter(task => task.due >= startDate && task.due <= localDate());
  const doneTasks = relevantTasks.filter(task => task.done);
  const overdue = data.tasks.filter(task => task.due && task.due < localDate() && !task.done);
  const dueChapters = data.subjects.flatMap(subject => subject.chapters.filter(chapter => !chapter.nextReview || chapter.nextReview <= localDate()).map(chapter => ({ chapter, subject })));
  const distractions = sessions.reduce((sum, session) => sum + session.distractions, 0);
  const subjectFocus = data.subjects.map(subject => ({ subject, minutes: sessions.filter(session => data.tasks.find(task => task.id === session.taskId)?.subjectId === subject.id).reduce((sum, session) => sum + session.minutes, 0) })).sort((a, b) => a.minutes - b.minutes);
  const suggestions = [
    ...(overdue.length ? [{ id: 'overdue', icon: <Flag size={18} />, title: 'Give unfinished work a fresh start.', description: `${overdue.length} open ${overdue.length === 1 ? 'task is' : 'tasks are'} past the planned date. Move the first one into your next priority block.`, action: 'Prioritize one task', run: () => { update(draft => { const task = draft.tasks.find(item => item.id === overdue[0].id); if (task) { task.quadrant = 'do'; task.due = dateOffset(1); } }); notify('Task moved to Do first, due tomorrow'); } }] : []),
    ...(dueChapters.length ? [{ id: 'recall', icon: <BookOpen size={18} />, title: 'Make a little room for recall.', description: `${dueChapters.length} chapters are ready for review. Begin with ${dueChapters[0].chapter.title}.`, action: 'Plan a review task', run: () => { const title = `Recall: ${dueChapters[0].chapter.title}`; if (data.tasks.some(task => task.title === title && !task.done)) { notify('This review task is already planned'); return; } update(draft => { draft.tasks.push({ id: uid(), title, subjectId: dueChapters[0].subject.id, quadrant: 'plan', done: false, due: dateOffset(1), minutes: 20, difficulty: 2, energy: 'medium', notes: 'Created during your weekly review.', subtasks: [], recurrence: 'none' }); }); notify('Review task added to Schedule'); } }] : []),
    ...(subjectFocus.length ? [{ id: 'balance', icon: <Target size={18} />, title: `A little attention for ${subjectFocus[0].subject.name}.`, description: `${duration(subjectFocus[0].minutes)} of focus went to this subject in the last 7 days. A short session could bring it back into balance.`, action: 'Add a 25-minute block', run: () => { const title = `${subjectFocus[0].subject.name} · focus`; if (data.events.some(event => event.title === title && event.date === dateOffset(1))) { notify('This focus block is already on tomorrow’s calendar'); return; } update(draft => { draft.events.push({ id: uid(), title, date: dateOffset(1), time: '10:00', minutes: 25, subjectId: subjectFocus[0].subject.id }); }); notify('Focus block added for tomorrow at 10:00'); } }] : []),
  ];
  function save(event: React.FormEvent) { event.preventDefault(); update(draft => { const existing = draft.reviews.find(review => review.date >= startDate && review.date <= localDate()); if (existing) Object.assign(existing, { wins, challenges, nextWeek }); else draft.reviews.unshift({ id: uid(), date: localDate(), wins, challenges, nextWeek }); }); notify('Weekly reflection saved'); }
  return <div className="page-stack learn-page"><PageHeading eyebrow="PAUSE. NOTICE. REALIGN." title="A fresh perspective on your week." description="Progress gets clearer when you give yourself a moment to look back." actions={<span className="badge">{dateLabel(startDate)} — {dateLabel(localDate())}</span>} />
    <Panel className="learn-week-banner"><div><span className="eyebrow">YOUR WEEKLY RESET</span><h2>You don’t need to do everything.<br /><em>Just what matters next.</em></h2><p>Reflect on the last seven days. Choose your next direction with intention.</p></div><span className="learn-week-symbol"><Sparkles size={54} strokeWidth={.9} /></span></Panel>
    <div className="learn-metric-grid"><Metric label="Focused effort" value={duration(minutes)} detail={`${Math.round(minutes / Math.max(1, data.settings.weeklyTarget * 60) * 100)}% of your weekly focus target`} icon={<Clock3 size={18} />} /><Metric label="Plans brought to life" value={<>{doneTasks.length}<small> / {relevantTasks.length}</small></>} detail="Completed tasks due in the last 7 days" icon={<CheckCircle2 size={18} />} /><Metric label="Times you showed up" value={sessions.length} detail={`${new Set(sessions.map(session => session.date.slice(0, 10))).size} different focus days this week`} icon={<TrendingUp size={18} />} /><Metric label="Attention check-ins" value={distractions} detail="Distractions logged in your focus sessions" icon={<Circle size={18} />} /></div>
    <div className="learn-strategy-grid"><Panel><span className="eyebrow">A CONVERSATION WITH YOURSELF</span><h2>What did this week teach you?</h2><form className="learn-reflection-form" onSubmit={save}><Field label="01 / What went well?"><textarea className="input" rows={4} value={wins} onChange={event => setWins(event.target.value)} placeholder="The small wins count, too…" /></Field><Field label="02 / What got in the way?"><textarea className="input" rows={4} value={challenges} onChange={event => setChallenges(event.target.value)} placeholder="Notice it without judging it…" /></Field><Field label="03 / What will you make room for next?"><textarea className="input" rows={4} value={nextWeek} onChange={event => setNextWeek(event.target.value)} placeholder="One to three priorities that matter…" /></Field><Button variant="primary" type="submit"><Check size={15} />Save my reflection</Button></form></Panel><div className="stack"><Panel><span className="eyebrow">FROM YOUR ACTUAL ACTIVITY</span><h2>A few thoughtful next steps.</h2><p className="muted">Suggestions based on your tasks, review dates, and recorded focus.</p><div className="learn-suggestions">{suggestions.map(suggestion => <div className="learn-suggestion" key={suggestion.id}><span className="learn-icon">{suggestion.icon}</span><div><h3>{suggestion.title}</h3><p>{suggestion.description}</p><button className="learn-text-button" onClick={suggestion.run}>{suggestion.action}<ArrowRight size={14} /></button></div></div>)}</div>{!suggestions.length && <p className="muted">Add a subject or a few tasks to see useful next steps here.</p>}</Panel><Panel><span className="eyebrow">YOUR REFLECTION ARCHIVE</span><h2>A record of becoming.</h2>{data.reviews.length ? <div className="learn-review-archive">{data.reviews.slice().sort((a, b) => b.date.localeCompare(a.date)).map(review => <details key={review.id}><summary><span>{dateLabel(review.date)}</span><ChevronRight size={16} /></summary><h4>What went well</h4><p>{review.wins || 'No reflection recorded.'}</p><h4>What got in the way</h4><p>{review.challenges || 'No reflection recorded.'}</p><h4>What comes next</h4><p>{review.nextWeek || 'No reflection recorded.'}</p></details>)}</div> : <p className="muted">Your saved reflections will live here.</p>}</Panel></div></div>
  </div>;
}
